// src/app/auth/register/register.component.ts
import { Component, type OnInit } from "@angular/core"
import { type FormBuilder, FormGroup, Validators } from "@angular/forms"
import type { Router } from "@angular/router"

@Component({
  selector: "app-register",
  templateUrl: "./register.component.html",
  styleUrls: ["./register.component.scss"],
})
export class RegisterComponent implements OnInit {
  registerForm!: FormGroup
  isLoading = false
  showPassword = false
  showConfirmPassword = false
  errorMessage = ""
  successMessage = ""

  constructor(
    private fb: FormBuilder,
    private router: Router,
  ) {}

  ngOnInit(): void {
    this.registerForm = this.fb.group(
      {
        fullName: ["", [Validators.required, Validators.minLength(3)]],
        email: ["", [Validators.required, Validators.email]],
        password: ["", [Validators.required, Validators.minLength(6)]],
        confirmPassword: ["", [Validators.required]],
      },
      {
        validators: this.passwordMatchValidator,
      },
    )
  }

  // Validador personalizado para verificar que las contraseñas coincidan
  passwordMatchValidator(form: FormGroup) {
    const password = form.get("password")?.value
    const confirmPassword = form.get("confirmPassword")?.value

    if (password !== confirmPassword) {
      form.get("confirmPassword")?.setErrors({ passwordMismatch: true })
      return { passwordMismatch: true }
    }

    return null
  }

  onSubmit(): void {
    if (this.registerForm.valid) {
      this.isLoading = true

      // Simulación de registro (reemplazar con llamada real al servicio)
      setTimeout(() => {
        this.isLoading = false
        this.successMessage = "¡Registro exitoso! Redirigiendo al inicio de sesión..."

        // Redireccionar después de mostrar el mensaje de éxito
        setTimeout(() => {
          this.router.navigate(["/auth/login"])
        }, 2000)
      }, 1500)
    } else {
      this.markFormGroupTouched(this.registerForm)
    }
  }

  togglePasswordVisibility(): void {
    this.showPassword = !this.showPassword
  }

  toggleConfirmPasswordVisibility(): void {
    this.showConfirmPassword = !this.showConfirmPassword
  }

  // Función auxiliar para marcar todos los campos como tocados
  private markFormGroupTouched(formGroup: FormGroup): void {
    Object.values(formGroup.controls).forEach((control) => {
      control.markAsTouched()
      if (control instanceof FormGroup) {
        this.markFormGroupTouched(control)
      }
    })
  }
}

<div class="p-8">
  <h2 class="text-2xl font-bold text-center text-gray-800 mb-6">Crear Cuenta</h2>
  
  <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="space-y-5">
    <!-- Nombre completo -->
    <div class="space-y-2">
      <label for="fullName" class="block text-sm font-medium text-gray-700">Nombre completo</label>
      <div class="relative">
        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd" />
          </svg>
        </div>
        <input 
          type="text" 
          id="fullName" 
          formControlName="fullName" 
          class="pl-10 w-full py-2 border border-gray-300 rounded-lg focus:ring-[#4dd0e1] focus:border-[#4dd0e1] transition duration-200"
          placeholder="Juan Pérez"
        >
      </div>
      <div *ngIf="registerForm.get('fullName')?.touched && registerForm.get('fullName')?.invalid" class="text-red-500 text-sm mt-1">
        <span *ngIf="registerForm.get('fullName')?.errors?.['required']">El nombre es obligatorio</span>
        <span *ngIf="registerForm.get('fullName')?.errors?.['minlength']">El nombre debe tener al menos 3 caracteres</span>
      </div>
    </div>
    
    <!-- Email -->
    <div class="space-y-2">
      <label for="email" class="block text-sm font-medium text-gray-700">Correo electrónico</label>
      <div class="relative">
        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
            <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" />
            <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" />
          </svg>
        </div>
        <input 
          type="email" 
          id="email" 
          formControlName="email" 
          class="pl-10 w-full py-2 border border-gray-300 rounded-lg focus:ring-[#4dd0e1] focus:border-[#4dd0e1] transition duration-200"
          placeholder="tu@email.com"
        >
      </div>
      <div *ngIf="registerForm.get('email')?.touched && registerForm.get('email')?.invalid" class="text-red-500 text-sm mt-1">
        <span *ngIf="registerForm.get('email')?.errors?.['required']">El correo es obligatorio</span>
        <span *ngIf="registerForm.get('email')?.errors?.['email']">Ingresa un correo válido</span>
      </div>
    </div>
    
    <!-- Contraseña -->
    <div class="space-y-2">
      <label for="password" class="block text-sm font-medium text-gray-700">Contraseña</label>
      <div class="relative">
        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
          </svg>
        </div>
        <input 
          [type]="showPassword ? 'text' : 'password'" 
          id="password" 
          formControlName="password" 
          class="pl-10 w-full py-2 border border-gray-300 rounded-lg focus:ring-[#4dd0e1] focus:border-[#4dd0e1] transition duration-200"
          placeholder="••••••••"
        >
        <button 
          type="button" 
          (click)="togglePasswordVisibility()" 
          class="absolute inset-y-0 right-0 pr-3 flex items-center"
        >
          <svg *ngIf="!showPassword" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
            <path d="M10 12a2 2 0 100-4 2 2 0 000 4z" />
            <path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd" />
          </svg>
          <svg *ngIf="showPassword" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M3.707 2.293a1 1 0 00-1.414 1.414l14 14a1 1 0 001.414-1.414l-1.473-1.473A10.014 10.014 0 0019.542 10C18.268 5.943 14.478 3 10 3a9.958 9.958 0 00-4.512 1.074l-1.78-1.781zm4.261 4.26l1.514 1.515a2.003 2.003 0 012.45 2.45l1.514 1.514a4 4 0 00-5.478-5.478z" clip-rule="evenodd" />
            <path d="M12.454 16.697L9.75 13.992a4 4 0 01-3.742-3.741L2.335 6.578A9.98 9.98 0 00.458 10c1.274 4.057 5.065 7 9.542 7 .847 0 1.669-.105 2.454-.303z" />
          </svg>
        </button>
      </div>
      <div *ngIf="registerForm.get('password')?.touched && registerForm.get('password')?.invalid" class="text-red-500 text-sm mt-1">
        <span *ngIf="registerForm.get('password')?.errors?.['required']">La contraseña es obligatoria</span>
        <span *ngIf="registerForm.get('password')?.errors?.['minlength']">La contraseña debe tener al menos 6 caracteres</span>
      </div>
    </div>
    
    <!-- Confirmar Contraseña -->
    <div class="space-y-2">
      <label for="confirmPassword" class="block text-sm font-medium text-gray-700">Confirmar contraseña</label>
      <div class="relative">
        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
          </svg>
        </div>
        <input 
          [type]="showConfirmPassword ? 'text' : 'password'" 
          id="confirmPassword" 
          formControlName="confirmPassword" 
          class="pl-10 w-full py-2 border border-gray-300 rounded-lg focus:ring-[#4dd0e1] focus:border-[#4dd0e1] transition duration-200"
          placeholder="••••••••"
        >
        <button 
          type="button" 
          (click)="toggleConfirmPasswordVisibility()" 
          class="absolute inset-y-0 right-0 pr-3 flex items-center"
        >
          <svg *ngIf="!showConfirmPassword" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
            <path d="M10 12a2 2 0 100-4 2 2 0 000 4z" />
            <path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd" />
          </svg>
          <svg *ngIf="showConfirmPassword" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M3.707 2.293a1 1 0 00-1.414 1.414l14 14a1 1 0 001.414-1.414l-1.473-1.473A10.014 10.014 0 0019.542 10C18.268 5.943 14.478 3 10 3a9.958 9.958 0 00-4.512 1.074l-1.78-1.781zm4.261 4.26l1.514 1.515a2.003 2.003 0 012.45 2.45l1.514 1.514a4 4 0 00-5.478-5.478z" clip-rule="evenodd" />
            <path d="M12.454 16.697L9.75 13.992a4 4 0 01-3.742-3.741L2.335 6.578A9.98 9.98 0 00.458 10c1.274 4.057 5.065 7 9.542 7 .847 0 1.669-.105 2.454-.303z" />
          </svg>
        </button>
      </div>
      <div *ngIf="registerForm.get('confirmPassword')?.touched && registerForm.get('confirmPassword')?.invalid" class="text-red-500 text-sm mt-1">
        <span *ngIf="registerForm.get('confirmPassword')?.errors?.['required']">Confirma tu contraseña</span>
        <span *ngIf="registerForm.get('confirmPassword')?.errors?.['passwordMismatch']">Las contraseñas no coinciden</span>
      </div>
    </div>
    
    <!-- Mensaje de error -->
    <div *ngIf="errorMessage" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <span class="block sm:inline">{{ errorMessage }}</span>
    </div>
    
    <!-- Mensaje de éxito -->
    <div *ngIf="successMessage" class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
      <span class="block sm:inline">{{ successMessage }}</span>
    </div>
    
    <!-- Botón de registro -->
    <button 
      type="submit" 
      [disabled]="isLoading" 
      class="w-full bg-[#4dd0e1] hover:bg-[#00acc1] text-white font-bold py-2 px-4 rounded-lg transition duration-200 flex justify-center items-center"
    >
      <span *ngIf="!isLoading">Registrarse</span>
      <div *ngIf="isLoading" class="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
    </button>
    
    <!-- Enlace a login -->
    <div class="text-center mt-4">
      <p class="text-sm text-gray-600">
        ¿Ya tienes cuenta? 
        <a routerLink="/auth/login" class="text-[#00796b] hover:underline font-medium">Inicia sesión</a>
      </p>
    </div>
  </form>
</div>

// app/components/RegisterComponent.tsx
"use client"

import type React from "react"

import { useState } from "react"
import { Eye, EyeOff, Mail, Lock, User, Loader2, CheckCircle } from "lucide-react"

interface RegisterComponentProps {
  onSwitchToLogin: () => void
}

export function RegisterComponent({ onSwitchToLogin }: RegisterComponentProps) {
  const [formData, setFormData] = useState({
    fullName: "",
    email: "",
    password: "",
    confirmPassword: "",
  })
  const [showPassword, setShowPassword] = useState(false)
  const [showConfirmPassword, setShowConfirmPassword] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [touched, setTouched] = useState<Record<string, boolean>>({})
  const [successMessage, setSuccessMessage] = useState("")

  const validateField = (name: string, value: string) => {
    switch (name) {
      case "fullName":
        if (!value) return "El nombre es obligatorio"
        if (value.length < 3) return "El nombre debe tener al menos 3 caracteres"
        return ""
      case "email":
        if (!value) return "El correo es obligatorio"
        if (!/\S+@\S+\.\S+/.test(value)) return "Ingresa un correo válido"
        return ""
      case "password":
        if (!value) return "La contraseña es obligatoria"
        if (value.length < 6) return "La contraseña debe tener al menos 6 caracteres"
        return ""
      case "confirmPassword":
        if (!value) return "Confirma tu contraseña"
        if (value !== formData.password) return "Las contraseñas no coinciden"
        return ""
      default:
        return ""
    }
  }

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target
    setFormData((prev) => ({ ...prev, [name]: value }))

    if (touched[name]) {
      const error = validateField(name, value)
      setErrors((prev) => ({ ...prev, [name]: error }))
    }

    // Validar confirmPassword cuando password cambie
    if (name === "password" && touched.confirmPassword) {
      const confirmError = formData.confirmPassword !== value ? "Las contraseñas no coinciden" : ""
      setErrors((prev) => ({ ...prev, confirmPassword: confirmError }))
    }
  }

  const handleBlur = (e: React.FocusEvent<HTMLInputElement>) => {
    const { name, value } = e.target
    setTouched((prev) => ({ ...prev, [name]: true }))
    const error = validateField(name, value)
    setErrors((prev) => ({ ...prev, [name]: error }))
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()

    // Validar todos los campos
    const newErrors: Record<string, string> = {}
    Object.keys(formData).forEach((key) => {
      const error = validateField(key, formData[key as keyof typeof formData])
      if (error) newErrors[key] = error
    })

    setErrors(newErrors)
    setTouched({ fullName: true, email: true, password: true, confirmPassword: true })

    if (Object.keys(newErrors).length === 0) {
      setIsLoading(true)
      // Simular llamada a la API
      setTimeout(() => {
        setIsLoading(false)
        setSuccessMessage("¡Registro exitoso! Redirigiendo al inicio de sesión...")
        setTimeout(() => {
          onSwitchToLogin()
        }, 2000)
      }, 1500)
    }
  }

  return (
    <div className="p-8">
      <h2 className="text-2xl font-bold text-center text-gray-800 mb-6">Crear Cuenta</h2>

      <form onSubmit={handleSubmit} className="space-y-5">
        {/* Nombre completo */}
        <div className="space-y-2">
          <label htmlFor="fullName" className="block text-sm font-medium text-gray-700">
            Nombre completo
          </label>
          <div className="relative">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <User className="h-5 w-5 text-gray-400" />
            </div>
            <input
              type="text"
              id="fullName"
              name="fullName"
              value={formData.fullName}
              onChange={handleInputChange}
              onBlur={handleBlur}
              className={`pl-10 w-full py-2 border rounded-lg focus:ring-2 focus:ring-[#4dd0e1] focus:border-[#4dd0e1] transition duration-200 ${
                errors.fullName && touched.fullName ? "border-red-500" : "border-gray-300"
              }`}
              placeholder="Juan Pérez"
            />
          </div>
          {errors.fullName && touched.fullName && <p className="text-red-500 text-sm mt-1">{errors.fullName}</p>}
        </div>

        {/* Email */}
        <div className="space-y-2">
          <label htmlFor="email" className="block text-sm font-medium text-gray-700">
            Correo electrónico
          </label>
          <div className="relative">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <Mail className="h-5 w-5 text-gray-400" />
            </div>
            <input
              type="email"
              id="email"
              name="email"
              value={formData.email}
              onChange={handleInputChange}
              onBlur={handleBlur}
              className={`pl-10 w-full py-2 border rounded-lg focus:ring-2 focus:ring-[#4dd0e1] focus:border-[#4dd0e1] transition duration-200 ${
                errors.email && touched.email ? "border-red-500" : "border-gray-300"
              }`}
              placeholder="tu@email.com"
            />
          </div>
          {errors.email && touched.email && <p className="text-red-500 text-sm mt-1">{errors.email}</p>}
        </div>

        {/* Contraseña */}
        <div className="space-y-2">
          <label htmlFor="password" className="block text-sm font-medium text-gray-700">
            Contraseña
          </label>
          <div className="relative">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <Lock className="h-5 w-5 text-gray-400" />
            </div>
            <input
              type={showPassword ? "text" : "password"}
              id="password"
              name="password"
              value={formData.password}
              onChange={handleInputChange}
              onBlur={handleBlur}
              className={`pl-10 pr-10 w-full py-2 border rounded-lg focus:ring-2 focus:ring-[#4dd0e1] focus:border-[#4dd0e1] transition duration-200 ${
                errors.password && touched.password ? "border-red-500" : "border-gray-300"
              }`}
              placeholder="••••••••"
            />
            <button
              type="button"
              onClick={() => setShowPassword(!showPassword)}
              className="absolute inset-y-0 right-0 pr-3 flex items-center"
            >
              {showPassword ? <EyeOff className="h-5 w-5 text-gray-400" /> : <Eye className="h-5 w-5 text-gray-400" />}
            </button>
          </div>
          {errors.password && touched.password && <p className="text-red-500 text-sm mt-1">{errors.password}</p>}
        </div>

        {/* Confirmar Contraseña */}
        <div className="space-y-2">
          <label htmlFor="confirmPassword" className="block text-sm font-medium text-gray-700">
            Confirmar contraseña
          </label>
          <div className="relative">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <Lock className="h-5 w-5 text-gray-400" />
            </div>
            <input
              type={showConfirmPassword ? "text" : "password"}
              id="confirmPassword"
              name="confirmPassword"
              value={formData.confirmPassword}
              onChange={handleInputChange}
              onBlur={handleBlur}
              className={`pl-10 pr-10 w-full py-2 border rounded-lg focus:ring-2 focus:ring-[#4dd0e1] focus:border-[#4dd0e1] transition duration-200 ${
                errors.confirmPassword && touched.confirmPassword ? "border-red-500" : "border-gray-300"
              }`}
              placeholder="••••••••"
            />
            <button
              type="button"
              onClick={() => setShowConfirmPassword(!showConfirmPassword)}
              className="absolute inset-y-0 right-0 pr-3 flex items-center"
            >
              {showConfirmPassword ? (
                <EyeOff className="h-5 w-5 text-gray-400" />
              ) : (
                <Eye className="h-5 w-5 text-gray-400" />
              )}
            </button>
          </div>
          {errors.confirmPassword && touched.confirmPassword && (
            <p className="text-red-500 text-sm mt-1">{errors.confirmPassword}</p>
          )}
        </div>

        {/* Mensaje de éxito */}
        {successMessage && (
          <div className="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative flex items-center">
            <CheckCircle className="h-5 w-5 mr-2" />
            <span className="block sm:inline">{successMessage}</span>
          </div>
        )}

        {/* Botón de registro */}
        <button
          type="submit"
          disabled={isLoading}
          className="w-full bg-[#4dd0e1] hover:bg-[#00acc1] disabled:opacity-50 text-white font-bold py-3 px-4 rounded-lg transition duration-200 flex justify-center items-center"
        >
          {isLoading ? <Loader2 className="h-5 w-5 animate-spin" /> : "Registrarse"}
        </button>

        {/* Enlace a login */}
        <div className="text-center mt-4">
          <p className="text-sm text-gray-600">
            ¿Ya tienes cuenta?{" "}
            <button type="button" onClick={onSwitchToLogin} className="text-[#00796b] hover:underline font-medium">
              Inicia sesión
            </button>
          </p>
        </div>
      </form>
    </div>
  )
}
