// src/app/auth/login/login.component.ts
import { Component, type OnInit } from "@angular/core"
import { type FormBuilder, FormGroup, Validators } from "@angular/forms"
import type { Router } from "@angular/router"

@Component({
  selector: "app-login",
  templateUrl: "./login.component.html",
  styleUrls: ["./login.component.scss"],
})
export class LoginComponent implements OnInit {
  loginForm!: FormGroup
  isLoading = false
  showPassword = false
  errorMessage = ""

  constructor(
    private fb: FormBuilder,
    private router: Router,
  ) {}

  ngOnInit(): void {
    this.loginForm = this.fb.group({
      email: ["", [Validators.required, Validators.email]],
      password: ["", [Validators.required, Validators.minLength(6)]],
    })
  }

  onSubmit(): void {
    if (this.loginForm.valid) {
      this.isLoading = true

      // Simulación de login (reemplazar con llamada real al servicio)
      setTimeout(() => {
        this.isLoading = false
        // Navegar a la página principal después del login exitoso
        this.router.navigate(["/dashboard"])
      }, 1500)
    } else {
      this.markFormGroupTouched(this.loginForm)
    }
  }

  togglePasswordVisibility(): void {
    this.showPassword = !this.showPassword
  }

  // Función auxiliar para marcar todos los campos como tocados
  private markFormGroupTouched(formGroup: FormGroup): void {
    Object.values(formGroup.controls).forEach((control) => {
      control.markAsTouched()
      if (control instanceof FormGroup) {
        this.markFormGroupTouched(control)
      }
    })
  }
}

<div class="p-8">
  <h2 class="text-2xl font-bold text-center text-gray-800 mb-6">Iniciar Sesión</h2>
  
  <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="space-y-6">
    <!-- Email -->
    <div class="space-y-2">
      <label for="email" class="block text-sm font-medium text-gray-700">Correo electrónico</label>
      <div class="relative">
        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
            <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z" />
            <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z" />
          </svg>
        </div>
        <input 
          type="email" 
          id="email" 
          formControlName="email" 
          class="pl-10 w-full py-2 border border-gray-300 rounded-lg focus:ring-[#4dd0e1] focus:border-[#4dd0e1] transition duration-200"
          placeholder="tu@email.com"
        >
      </div>
      <div *ngIf="loginForm.get('email')?.touched && loginForm.get('email')?.invalid" class="text-red-500 text-sm mt-1">
        <span *ngIf="loginForm.get('email')?.errors?.['required']">El correo es obligatorio</span>
        <span *ngIf="loginForm.get('email')?.errors?.['email']">Ingresa un correo válido</span>
      </div>
    </div>
    
    <!-- Contraseña -->
    <div class="space-y-2">
      <label for="password" class="block text-sm font-medium text-gray-700">Contraseña</label>
      <div class="relative">
        <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clip-rule="evenodd" />
          </svg>
        </div>
        <input 
          [type]="showPassword ? 'text' : 'password'" 
          id="password" 
          formControlName="password" 
          class="pl-10 w-full py-2 border border-gray-300 rounded-lg focus:ring-[#4dd0e1] focus:border-[#4dd0e1] transition duration-200"
          placeholder="••••••••"
        >
        <button 
          type="button" 
          (click)="togglePasswordVisibility()" 
          class="absolute inset-y-0 right-0 pr-3 flex items-center"
        >
          <svg *ngIf="!showPassword" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
            <path d="M10 12a2 2 0 100-4 2 2 0 000 4z" />
            <path fill-rule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd" />
          </svg>
          <svg *ngIf="showPassword" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M3.707 2.293a1 1 0 00-1.414 1.414l14 14a1 1 0 001.414-1.414l-1.473-1.473A10.014 10.014 0 0019.542 10C18.268 5.943 14.478 3 10 3a9.958 9.958 0 00-4.512 1.074l-1.78-1.781zm4.261 4.26l1.514 1.515a2.003 2.003 0 012.45 2.45l1.514 1.514a4 4 0 00-5.478-5.478z" clip-rule="evenodd" />
            <path d="M12.454 16.697L9.75 13.992a4 4 0 01-3.742-3.741L2.335 6.578A9.98 9.98 0 00.458 10c1.274 4.057 5.065 7 9.542 7 .847 0 1.669-.105 2.454-.303z" />
          </svg>
        </button>
      </div>
      <div *ngIf="loginForm.get('password')?.touched && loginForm.get('password')?.invalid" class="text-red-500 text-sm mt-1">
        <span *ngIf="loginForm.get('password')?.errors?.['required']">La contraseña es obligatoria</span>
        <span *ngIf="loginForm.get('password')?.errors?.['minlength']">La contraseña debe tener al menos 6 caracteres</span>
      </div>
    </div>
    
    <!-- Mensaje de error -->
    <div *ngIf="errorMessage" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <span class="block sm:inline">{{ errorMessage }}</span>
    </div>
    
    <!-- Botón de inicio de sesión -->
    <button 
      type="submit" 
      [disabled]="isLoading" 
      class="w-full bg-[#4dd0e1] hover:bg-[#00acc1] text-white font-bold py-2 px-4 rounded-lg transition duration-200 flex justify-center items-center"
    >
      <span *ngIf="!isLoading">Iniciar Sesión</span>
      <div *ngIf="isLoading" class="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
    </button>
    
    <!-- Enlace a registro -->
    <div class="text-center mt-4">
      <p class="text-sm text-gray-600">
        ¿No tienes cuenta? 
        <a routerLink="/auth/register" class="text-[#00796b] hover:underline font-medium">Regístrate</a>
      </p>
    </div>
  </form>
</div>

// app/components/auth/LoginComponent.tsx
"use client"

import type React from "react"

import { useState } from "react"
import { Eye, EyeOff, Mail, Lock, Loader2 } from "lucide-react"

interface LoginComponentProps {
  onLogin: (userData: any) => void
  onSwitchToRegister: () => void
}

export function LoginComponent({ onLogin, onSwitchToRegister }: LoginComponentProps) {
  const [formData, setFormData] = useState({ email: "", password: "" })
  const [showPassword, setShowPassword] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [errors, setErrors] = useState<Record<string, string>>({})

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    setIsLoading(true)

    setTimeout(() => {
      setIsLoading(false)
      onLogin({
        id: "1",
        fullName: "Juan Pérez",
        email: formData.email,
        role: formData.email.includes("admin") ? "moderador" : "estudiante",
      })
    }, 1500)
  }

  return (
    <div className="p-8">
      <h2 className="text-2xl font-bold text-center text-gray-800 mb-6">Iniciar Sesión</h2>

      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="space-y-2">
          <label className="block text-sm font-medium text-gray-700">Correo electrónico</label>
          <div className="relative">
            <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-gray-400" />
            <input
              type="email"
              value={formData.email}
              onChange={(e) => setFormData({ ...formData, email: e.target.value })}
              className="pl-10 w-full py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#4dd0e1] focus:border-[#4dd0e1]"
              placeholder="tu@email.com"
              required
            />
          </div>
        </div>

        <div className="space-y-2">
          <label className="block text-sm font-medium text-gray-700">Contraseña</label>
          <div className="relative">
            <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-gray-400" />
            <input
              type={showPassword ? "text" : "password"}
              value={formData.password}
              onChange={(e) => setFormData({ ...formData, password: e.target.value })}
              className="pl-10 pr-10 w-full py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-[#4dd0e1] focus:border-[#4dd0e1]"
              placeholder="••••••••"
              required
            />
            <button
              type="button"
              onClick={() => setShowPassword(!showPassword)}
              className="absolute right-3 top-1/2 transform -translate-y-1/2"
            >
              {showPassword ? <EyeOff className="h-5 w-5 text-gray-400" /> : <Eye className="h-5 w-5 text-gray-400" />}
            </button>
          </div>
        </div>

        <button
          type="submit"
          disabled={isLoading}
          className="w-full bg-[#4dd0e1] hover:bg-[#00acc1] disabled:opacity-50 text-white font-bold py-3 px-4 rounded-lg transition duration-200 flex justify-center items-center"
        >
          {isLoading ? <Loader2 className="h-5 w-5 animate-spin" /> : "Iniciar Sesión"}
        </button>

        <div className="text-center">
          <p className="text-sm text-gray-600">
            ¿No tienes cuenta?{" "}
            <button type="button" onClick={onSwitchToRegister} className="text-[#00796b] hover:underline font-medium">
              Regístrate
            </button>
          </p>
        </div>
      </form>
    </div>
  )
}
